project:
  type: website
  output-dir: docs

website:
  title: "ACP-25 Data Exploration"
#  navbar:
#    left:
#      - href: index.ipynb
#        text: Home
#      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



